FROM node:8.12.0-alpine
WORKDIR "/app"
COPY ./package*.json ./
RUN apk add --no-cache \
    build-base \
    g++ \
    cairo-dev \
    jpeg-dev \
    pango-dev \
    giflib-dev
RUN npm install --only=production
COPY . .
RUN npm run build --no-cache
CMD ["npm", "run", "server"]
