debug = false

defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
	[entryPoints.dashboard]
	address=":8080"

[api]
entrypoint = "dashboard"
[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker.localhost"
watch = true
exposedbydefault = false
